FROM node:18-alpine

# Define o diretório de trabalho
WORKDIR /app

CMD ["tail", "-f", "/dev/null"]
# Exponha a porta padrão do Vite/Vue
EXPOSE 5173

# Comando para iniciar a aplicação em modo desenvolvimento
# CMD ["npm", "run", "dev", "--", "--host"]
