
services:
  db:
    image: postgres:15-alpine
    container_name: roteirizador_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  management-api:
    build: ./management-api
    container_name: roteirizador_management_api
    command: bash -c "bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./management-api:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      RAILS_ENV: development

  routing-api:
    build: ./routing-api
    container_name: roteirizador_routing_api
    volumes:
      - ./routing-api:/app
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    container_name: roteirizador_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"

volumes:
  pg_data: